### ISSUE TITLE
Link to github.io page

### ISSUE THREAD

**Issue by keikoro** [tullyhansen/NaBoMaMo#1]
Hi there,

Mightn't it make sense to link to the actual NaBoMaMo site from the repo's README? I just googled the whole thing again after discovering it yesterday, but couldn't find it anymore and the repo isn't really obvious about it either.

**Comment by tullyhansen** [comment]
Hey @kerstin, excellent point, will try and get to today when I'm back on my Mac. Thanks for taking the time to point out.

**Comment by tullyhansen** [comment]
Should really use Jekyll to pull page content from README.md, but for now have copied website text to the readme. #88e3b859ea8e5b5ce5118f7f90b92c0baffe058c

**Comment by tullyhansen** [comment]
Wow, I _do not_ know how to close a GitHub issue.

**Comment by keikoro** [comment]
Ohh, I think a link to the github.io page would have been sufficient. :P 
You probably don't want to maintain the same text content in two different places!
